name: Build iOS IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Selecionar Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Instalar XcodeGen
        run: brew install xcodegen

      - name: Gerar Projeto Xcode (.xcodeproj)
        run: |
          cd ios/FinancasApp
          xcodegen generate

      - name: Compilar App para iOS
        run: |
          cd ios/FinancasApp
          xcodebuild -project FinancasApp.xcodeproj \
            -scheme FinancasApp \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES \
            build

      - name: Empacotar em arquivo IPA
        run: |
          mkdir -p Payload
          cp -r ios/FinancasApp/build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r FinancasApp.ipa Payload
          rm -rf Payload

      - name: Disponibilizar IPA para Download
        uses: actions/upload-artifact@v4
        with:
          name: FinancasApp-IPA
          path: FinancasApp.ipa